name: Build and Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        jdk: [zulu@1.8.242, zulu@1.11.0-6, zulu@1.13.0, graalvm@20.0.0]
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT ivy cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Set up JDK ${{ matrix.jdk }}
        uses: olafurpg/setup-scala@v5
        with:
          java-version: ${{ matrix.jdk }}
      - name: Run tests
        run: sbt test
  docu:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK zulu@1.11.0
        uses: olafurpg/setup-scala@v5
        with:
          java-version: zulu@1.11.0-6
      - name: Build Docu
        run: sbt paradox
      - name: Deploy Docu
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/paradox/site/main
          GIT_CONFIG_NAME: QuadStingray CI
          GIT_CONFIG_EMAIL: ci@quadstingray.com
          CLEAN: true
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK zulu@1.11.0
        uses: olafurpg/setup-scala@v5
        with:
          java-version: zulu@1.11.0-6
      - name: Release
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_TOKEN: ${{ secrets.BINTRAY_TOKEN }}
        run: |
          if grep -q "SNAPSHOT" version.sbt
          then
              echo 'Nothing to do';
          else
            git config --global user.email "ci@quadstingray.com"
            git config --global user.name "QuadStingray CI"
            sbt -Dbintray.user=$BINTRAY_USER -Dbintray.pass=$BINTRAY_TOKEN "release with-defaults"
          fi
