name: Scala Cross Check all OS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        jdk: [zulu@1.8.242, zulu@1.11.0-6, zulu@1.13.0, graalvm@20.0.0]
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.jdk }}
      uses: olafurpg/setup-scala@v5
      with:
        java-version: ${{ matrix.jdk }}
    - name: Run tests
      run: sbt test

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK zulu@1.13.0
        uses: olafurpg/setup-scala@v5
        with:
          java-version: zulu@1.13.0
      - name: Build Docu
        run: |
          if grep -q "SNAPSHOT" version.sbt
          then
              echo 'Nothing to do';
          else
            sbt paradox ghpagesPushSite
          fi
      - name: Release
        run: |
          if grep -q "SNAPSHOT" version.sbt
          then
              echo 'Nothing to do';
          else
            sbt "release with-defaults"
          fi