name: Scala Steward Dependency Check

# This workflow will launch at 00:00 every Sunday
on:
  schedule:    
    - cron:  '0 0 * * 0'
  repository_dispatch:
    types: [scala-steward]

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}
          sign-commits: false
          author-email: ci@quadstingray.com
          author-name: Scala Steward
